services:
  postgres:
    image: postgres:17
    container_name: rust_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: rust
      POSTGRES_PASSWORD: rust123
      POSTGRES_DB: rust_api

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: